#端口号
server:
  port: 8080
  servlet:
    session:
      cookie:
        max-age: 36000
spring:
  #数据库的配置信息
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.36.15.103:3306/chat_android?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 926496wyyw
  servlet:
    multipart:
      max-file-size: 10MB
mybatis:
  #开启驼峰命名法
#  configuration:
#    map-underscore-to-camel-case: true
mybatis-plus:
  # xml地址
  mapper-locations: classpath:mapper/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com/wangyou/websocketforandroid/entity   #自己的实体类地址
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl